### ISSUE TITLE
Clean up dataset

### ISSUE THREAD

**Issue by atzeus** [NLeSC/mcfly-tutorial#19]
The current dataset contain a couple of classes which hardly has any representatives. These make training longer, make the confusion matrix bigger, and overall complicate things, distracting from what should be a nice, simple example. 

I propose to remove the following classes from the dataset:
* rope_jumping
* ascending_stairs  
* descending_stairs
* running

**Comment by dafnevk** [comment]
Fixed in commit 6396453cb0ccd23260a59b21258b076f31c5098c . The new dataset can be found on [Zenodo](https://zenodo.org/record/834467)
