### ISSUE TITLE
Add explanation to visualiziation

### ISSUE THREAD

**Issue by vincentvanhees** [NLeSC/mcfly-tutorial#4]
@dafnevk commented on [Thu Mar 02 2017](https://github.com/NLeSC/mcfly/issues/120)

Add an information box that explains what file should be uploaded and what the default location might be

**Comment by cwmeijer** [comment]
Added some text. I think this should be enough.
See https://github.com/NLeSC/mcfly/commit/862a262674fb8beb78a2e6c1321b382a8b19929e
![temp](https://cloud.githubusercontent.com/assets/6087314/23699339/08a847e0-03ef-11e7-9ded-09ae17a36164.png)
