### ISSUE TITLE
All sequences in the data set should be of equal length.

### ISSUE THREAD

**Issue by rymoore** [NLeSC/mcfly-tutorial#43]
In the documentation, it is specified that "All sequences in the data set should be of equal length.". What is the recommended approach for dealing with Multichannel time series event classification using samples with variable length? Zero padding perhaps?

**Comment by cwmeijer** [comment]
This really depends on the problem. Zero padding might make sense for some cases, but using interpolation to create sequences of equal length will work better in other cases. Please reopen if this didn't help you.
